### ISSUE TITLE
User can view the app.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/ajax-project#1]

**Comment by vivianevieira** [comment]
## 💰 Motivation

Users can search for surf locations by city or beach name.

## 📐 Plan

Create a responsive page where users can search for a city or surf spots from anywhere in the world and check the current surf conditions.

## 🖼️ Wireframe


![Screen Shot 2020-11-10 at 11 15 31 AM](https://user-images.githubusercontent.com/71540857/98722914-84f0f980-2346-11eb-93df-c4270176e40f.png)

## ✅ Task List

- [ ] Pick a font from Google Fonts.
- [ ] Pick accent colors.
- [ ] Create a header that shows the name of application and also includes a search button and ellipse.
- [ ] Create a form and add an input field where users will be search for locations. 
- [ ] Add a submit button
- [ ] Apply fonts to heading, text, button, and form input field.
- [ ] Make input ‘required’
- [ ] Create an ul element inside the body and give an ID attribute with value “locations-list”
- [ ] Create a data model to store the value submitted on the input field, the locations longitude, latitude, and formatted location name.
- [ ] Query the form.
- [ ] Listen for ‘submit’ events on the form.
- [ ] Store the value of the input field on the data model.
- [ ] Query the DOM for the “#locations-list” element.
- [ ] Create an XMLHttpRequest inside a function that will get data from the Geogocode API.
   - [ ] Include the value that the user submitted on the input field into the URL that will be used to create the HTTP request.
   - [ ] Loop through the response of the request object.
   - [ ] For each object in the response, create an li element, set its textContent to the “formatted” property (this is where the location name will be nicely formatted), and append it to the '#user-list' element
- [ ] Call the function to begin loading the data from the server.
