### ISSUE TITLE
User can check the current surf conditions for a location anywhere in the world.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/ajax-project#3]

**Comment by vivianevieira** [comment]
## 💰 Motivation

Users want to check as many details as possible for a specific location.

## 📐 Plan

Create a surf check page where surf related data will be shown for the selected location.

## 🖼️ Wireframe

![Screen Shot 2020-11-11 at 10 27 33 AM](https://user-images.githubusercontent.com/71540857/98849758-8e429a80-2408-11eb-92df-4ec6f1bfcd48.png)


## ✅ Task List

- [ ] Make sure the li elements are  clickable links.
- [ ] Style them so they match the wireframe.
- [ ] On the getCoordinates function, set a data-view attribute with value “surf-check” on each of the li element.
- [ ] Listen for click events on the li element.
- [ ] Update the data model with each one of the attributes from the clicked li element.
- [ ] Hide the “search-page” data-view with using a CSS class attribute.
- [ ] Create a “surf-check” data-view page.
- [ ] Design the page in HTML to match the wireframe.
- [ ] Add sample data as shown on the wireframe.
- [ ] Create an XMLHttpRequest to get the surf data.
- [ ] On load, append the values on the appropriate elements from the DOM.
- [ ] Create a view swapping function that takes the user from the search page to the ‘surf check’ page once the user has clicked on link for one of the locations.
- [ ] Test the functionality. 
- [ ]Remove any CSS styling that’s not being used and/or any commented out code(s).
