### ISSUE TITLE
User can save a surf location to their ‘favorites’ list.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/ajax-project#4]

**Comment by vivianevieira** [comment]
## 💰 Motivation

Users will want to create a ‘favorites’ list so they can access the surf check for their favorite spots.

## 📐 Plan

Create a favorites button that allow users to start adding surf spots to a ‘favorites’ list.

## 🖼️ Wireframe

![Screen Shot 2020-11-12 at 11 07 58 AM](https://user-images.githubusercontent.com/71540857/98984676-6110ed80-24d7-11eb-95ea-072228d9ef84.png)
![Screen Shot 2020-11-12 at 11 08 06 AM](https://user-images.githubusercontent.com/71540857/98984683-63734780-24d7-11eb-82db-d2988d9736d5.png)


## ✅ Task List
- [ ] Design and add a ‘favorites’ icon to be placed on the top-right corner of the page, by the surf spot’s name.
- [ ] The icon  should be greyed out since there are no favorites yet.
- [ ] Listen for click events on the favorite button.
   - [ ] Once the button is clicked, the location name, lat and long are pushed to the array on the data model.
   - [ ] The button changes color once it is clicked on.
- [ ] Save the data to the local storage on reload.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again
