### ISSUE TITLE
User can view a list of their favorite locations.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/ajax-project#5]

**Comment by vivianevieira** [comment]
## 💰 Motivation

Users will want to access a list of their favorite surf spots :surfing_woman:

## 📐 Plan

Create a page view where users can see a list of the surf locations that have been saved as their ‘favorites’.
## 🖼️ Wireframe

![Screen Shot 2020-11-13 at 10 12 58 AM](https://user-images.githubusercontent.com/71540857/99106365-fc1dcc00-2598-11eb-8299-b2cfcf70a4b1.png)



## ✅ Task List

- [ ] Create a data-view for favorite spots and hide the other data-views.
- [ ] Design the page to match the wireframe and populate with sample data for a couple of example locations.
- [ ] Make sure the favorites icon on the footer is highlighted on this view.
- [ ] Pull the data from the local storage and append the location’s full name.
- [ ] Make the li elements clickable.
- [ ] After clicking on a location, the user should be taken to the surf check page view.
- [ ] On the surf check page, the favorite/heart icon should be blue, as the user will be looking at a favorited surf spot.
- [ ] Make sure data.location (not favorites) is deleted on load.
