### ISSUE TITLE
The user will see a personalized wave model on the surf check page.

### ISSUE THREAD

**Issue by vivianevieira** [vivianevieira/ajax-project#6]
## 💰 Motivation

Users want to see a wave model of the wave height and direction for a more graphic representation.

## 📐 Plan

Add a personalized wave model to the top of the surf check page. 

## 🖼️ Wireframe
![Screen Shot 2020-11-13 at 3 43 47 PM](https://user-images.githubusercontent.com/71540857/99131531-42d6ea80-25c8-11eb-99d9-e49e45b64a90.png)

![Screen Shot 2020-11-13 at 3 48 19 PM](https://user-images.githubusercontent.com/71540857/99131421-f25f8d00-25c7-11eb-9764-0501ed299fde.png)

## ✅ Task List

- [x] Create an http request for the Geotag API when the surf check page loads.
- [x] Get the data on the response that shows the continent, country and state.
- [x] Use the correct image source for the wave model according to the locations continent, country or state.
- [x] Test the functionality.
